#include "sprites.h"

// Project includes
#include "minigin/core/sprite_manager.h"

namespace qbert
{
    void register_sprites()
    {
        using namespace mngn;
        sprite_manager::instance()
            .set_sprite_config_path("configs/sprite_config.json")
            .load_sprite_config();

        sprite_manager::instance()
            .register_sprite(qb_sp_qbert_player_1, "qbert_player_1")
            .register_sprite(qb_sp_qbert_player_2, "qbert_player_2")
            .register_sprite(qb_sp_ball_red, "ball_red")
            .register_sprite(qb_sp_ball_green, "ball_green")
            .register_sprite(qb_sp_coily_egg, "coily_egg")
            .register_sprite(qb_sp_coily, "coily")
            .register_sprite(qb_sp_ugg, "ugg")
            .register_sprite(qb_sp_wrong_way, "wrong_way")
            .register_sprite(qb_sp_slick, "slick")
            .register_sprite(qb_sp_sam, "sam")
        
            .register_sprite(qb_sp_numbers_regular_orange, "numbers_regular_orange")
            .register_sprite(qb_sp_numbers_regular_purple, "numbers_regular_purple")
            .register_sprite(qb_sp_numbers_bold_orange, "numbers_bold_orange")
            .register_sprite(qb_sp_numbers_bold_pink, "numbers_bold_pink")
            .register_sprite(qb_sp_numbers_large_yellow, "numbers_large_yellow")
            .register_sprite(qb_sp_numbers_large_gray, "numbers_large_gray")
        
            .register_sprite(qb_sp_alphabet_regular_green, "alphabet_regular_green")
            .register_sprite(qb_sp_alphabet_regular_purple, "alphabet_regular_purple")
            .register_sprite(qb_sp_alphabet_regular_special, "alphabet_regular_special")
            .register_sprite(qb_sp_alphabet_regular_space, "alphabet_regular_space")
            .register_sprite(qb_sp_alphabet_bold_orange, "alphabet_bold_orange")
            .register_sprite(qb_sp_alphabet_large_yellow, "alphabet_large_yellow")
            .register_sprite(qb_sp_alphabet_large_gray, "alphabet_large_gray")
            .register_sprite(qb_sp_alphabet_large_space, "alphabet_large_space")
            .register_sprite(qb_sp_alphabet_large_special_yellow, "alphabet_large_special_yellow")
            .register_sprite(qb_sp_alphabet_large_special_gray, "alphabet_large_special_gray")
        
            .register_sprite(qb_sp_text_orange_player, "text_orange_player")
            .register_sprite(qb_sp_text_purple_player, "text_purple_player")
            .register_sprite(qb_sp_text_level, "text_level")
            .register_sprite(qb_sp_text_round, "text_round")
            .register_sprite(qb_sp_text_change_to, "text_change_to")
            .register_sprite(qb_sp_text_qbert, "text_qbert")
            .register_sprite(qb_sp_text_rotate_disk_color, "text_rotate_disk_color")
            .register_sprite(qb_sp_text_one, "text_one")
            .register_sprite(qb_sp_text_two, "text_two")
            .register_sprite(qb_sp_text_large_yellow_qbert, "text_large_yellow_qbert")
            .register_sprite(qb_sp_text_large_gray_qbert, "text_large_gray_qbert")
            .register_sprite(qb_sp_text_rub, "text_rub")
            .register_sprite(qb_sp_text_end, "text_end")
            .register_sprite(qb_sp_text_level_1, "text_level_1")
            .register_sprite(qb_sp_text_level_2, "text_level_2")
            .register_sprite(qb_sp_text_level_3, "text_level_3")
        
            .register_sprite(qb_sp_arrow_left, "arrow_left")
            .register_sprite(qb_sp_arrow_right, "arrow_right")
            .register_sprite(qb_sp_qbert_life, "qbert_life")
            .register_sprite(qb_sp_qbert_swearing, "qbert_swearing")
            .register_sprite(qb_sp_qbert_big, "qbert_big")
            .register_sprite(qb_sp_black_square, "black_square")
            .register_sprite(qb_sp_green_cirlce, "green_circle")
        
            .register_sprite(qb_sp_level_1_disk_1, "level_1_disk_1")
            .register_sprite(qb_sp_level_1_disk_2, "level_1_disk_2")
            .register_sprite(qb_sp_level_2_disk_1, "level_2_disk_1")
            .register_sprite(qb_sp_level_2_disk_2, "level_2_disk_2")
            .register_sprite(qb_sp_level_3_disk_1, "level_3_disk_1")
            .register_sprite(qb_sp_level_3_disk_2, "level_3_disk_2")
            .register_sprite(qb_sp_level_4_disk_1, "level_4_disk_1")
            .register_sprite(qb_sp_level_4_disk_2, "level_4_disk_2")
            .register_sprite(qb_sp_level_5_disk_1, "level_5_disk_1")
            .register_sprite(qb_sp_level_5_disk_2, "level_5_disk_2")
            .register_sprite(qb_sp_level_6_disk_1, "level_6_disk_1")
            .register_sprite(qb_sp_level_6_disk_2, "level_6_disk_2")
            .register_sprite(qb_sp_level_7_disk_1, "level_7_disk_1")
            .register_sprite(qb_sp_level_7_disk_2, "level_7_disk_2")
            .register_sprite(qb_sp_level_8_disk_1, "level_8_disk_1")
            .register_sprite(qb_sp_level_8_disk_2, "level_8_disk_2")
            .register_sprite(qb_sp_level_9_disk_1, "level_9_disk_1")
            .register_sprite(qb_sp_level_9_disk_2, "level_9_disk_2")
        
            .register_sprite(qb_sp_level_1_cube_1, "level_1_cube_1")
            .register_sprite(qb_sp_level_1_cube_2, "level_1_cube_2")
            .register_sprite(qb_sp_level_1_cube_3, "level_1_cube_3")
            .register_sprite(qb_sp_level_1_cube_4, "level_1_cube_4")
            .register_sprite(qb_sp_level_1_cube_5, "level_1_cube_5")
            .register_sprite(qb_sp_level_1_cube_6, "level_1_cube_6")
            .register_sprite(qb_sp_level_2_cube_1, "level_2_cube_1")
            .register_sprite(qb_sp_level_2_cube_2, "level_2_cube_2")
            .register_sprite(qb_sp_level_2_cube_3, "level_2_cube_3")
            .register_sprite(qb_sp_level_2_cube_4, "level_2_cube_4")
            .register_sprite(qb_sp_level_2_cube_5, "level_2_cube_5")
            .register_sprite(qb_sp_level_2_cube_6, "level_2_cube_6")
            .register_sprite(qb_sp_level_3_cube_1, "level_3_cube_1")
            .register_sprite(qb_sp_level_3_cube_2, "level_3_cube_2")
            .register_sprite(qb_sp_level_3_cube_3, "level_3_cube_3")
            .register_sprite(qb_sp_level_3_cube_4, "level_3_cube_4")
            .register_sprite(qb_sp_level_3_cube_5, "level_3_cube_5")
            .register_sprite(qb_sp_level_3_cube_6, "level_3_cube_6")
            .register_sprite(qb_sp_level_4_cube_1, "level_4_cube_1")
            .register_sprite(qb_sp_level_4_cube_2, "level_4_cube_2")
            .register_sprite(qb_sp_level_4_cube_3, "level_4_cube_3")
            .register_sprite(qb_sp_level_4_cube_4, "level_4_cube_4")
            .register_sprite(qb_sp_level_4_cube_5, "level_4_cube_5")
            .register_sprite(qb_sp_level_4_cube_6, "level_4_cube_6")
            .register_sprite(qb_sp_level_5_cube_1, "level_5_cube_1")
            .register_sprite(qb_sp_level_5_cube_2, "level_5_cube_2")
            .register_sprite(qb_sp_level_5_cube_3, "level_5_cube_3")
            .register_sprite(qb_sp_level_5_cube_4, "level_5_cube_4")
            .register_sprite(qb_sp_level_5_cube_5, "level_5_cube_5")
            .register_sprite(qb_sp_level_5_cube_6, "level_5_cube_6")
            .register_sprite(qb_sp_level_6_cube_1, "level_6_cube_1")
            .register_sprite(qb_sp_level_6_cube_2, "level_6_cube_2")
            .register_sprite(qb_sp_level_6_cube_3, "level_6_cube_3")
            .register_sprite(qb_sp_level_6_cube_4, "level_6_cube_4")
            .register_sprite(qb_sp_level_6_cube_5, "level_6_cube_5")
            .register_sprite(qb_sp_level_6_cube_6, "level_6_cube_6")
            .register_sprite(qb_sp_level_7_cube_1, "level_7_cube_1")
            .register_sprite(qb_sp_level_7_cube_2, "level_7_cube_2")
            .register_sprite(qb_sp_level_7_cube_3, "level_7_cube_3")
            .register_sprite(qb_sp_level_7_cube_4, "level_7_cube_4")
            .register_sprite(qb_sp_level_7_cube_5, "level_7_cube_5")
            .register_sprite(qb_sp_level_7_cube_6, "level_7_cube_6")
            .register_sprite(qb_sp_level_8_cube_1, "level_8_cube_1")
            .register_sprite(qb_sp_level_8_cube_2, "level_8_cube_2")
            .register_sprite(qb_sp_level_8_cube_3, "level_8_cube_3")
            .register_sprite(qb_sp_level_8_cube_4, "level_8_cube_4")
            .register_sprite(qb_sp_level_8_cube_5, "level_8_cube_5")
            .register_sprite(qb_sp_level_8_cube_6, "level_8_cube_6")
            .register_sprite(qb_sp_level_9_cube_1, "level_9_cube_1")
            .register_sprite(qb_sp_level_9_cube_2, "level_9_cube_2")
            .register_sprite(qb_sp_level_9_cube_3, "level_9_cube_3")
            .register_sprite(qb_sp_level_9_cube_4, "level_9_cube_4")
            .register_sprite(qb_sp_level_9_cube_5, "level_9_cube_5")
            .register_sprite(qb_sp_level_9_cube_6, "level_9_cube_6")
        
            .register_sprite(qb_sp_level_1_cube_1_small, "level_1_cube_1_small")
            .register_sprite(qb_sp_level_1_cube_2_small, "level_1_cube_2_small")
            .register_sprite(qb_sp_level_1_cube_3_small, "level_1_cube_3_small")
            .register_sprite(qb_sp_level_2_cube_1_small, "level_2_cube_1_small")
            .register_sprite(qb_sp_level_2_cube_2_small, "level_2_cube_2_small")
            .register_sprite(qb_sp_level_2_cube_3_small, "level_2_cube_3_small")
            .register_sprite(qb_sp_level_3_cube_1_small, "level_3_cube_1_small")
            .register_sprite(qb_sp_level_3_cube_2_small, "level_3_cube_2_small")
            .register_sprite(qb_sp_level_3_cube_3_small, "level_3_cube_3_small")
            .register_sprite(qb_sp_level_4_cube_1_small, "level_4_cube_1_small")
            .register_sprite(qb_sp_level_4_cube_2_small, "level_4_cube_2_small")
            .register_sprite(qb_sp_level_4_cube_3_small, "level_4_cube_3_small")
            .register_sprite(qb_sp_level_5_cube_1_small, "level_5_cube_1_small")
            .register_sprite(qb_sp_level_5_cube_2_small, "level_5_cube_2_small")
            .register_sprite(qb_sp_level_5_cube_3_small, "level_5_cube_3_small")
            .register_sprite(qb_sp_level_6_cube_1_small, "level_6_cube_1_small")
            .register_sprite(qb_sp_level_6_cube_2_small, "level_6_cube_2_small")
            .register_sprite(qb_sp_level_6_cube_3_small, "level_6_cube_3_small")
            .register_sprite(qb_sp_level_7_cube_1_small, "level_7_cube_1_small")
            .register_sprite(qb_sp_level_7_cube_2_small, "level_7_cube_2_small")
            .register_sprite(qb_sp_level_7_cube_3_small, "level_7_cube_3_small")
            .register_sprite(qb_sp_level_8_cube_1_small, "level_8_cube_1_small")
            .register_sprite(qb_sp_level_8_cube_2_small, "level_8_cube_2_small")
            .register_sprite(qb_sp_level_8_cube_3_small, "level_8_cube_3_small")
            .register_sprite(qb_sp_level_9_cube_1_small, "level_9_cube_1_small")
            .register_sprite(qb_sp_level_9_cube_2_small, "level_9_cube_2_small")
            .register_sprite(qb_sp_level_9_cube_3_small, "level_9_cube_3_small")

            .register_sprite(qb_sp_level_1_cube_animated, "level_1_cube_animated")
            .register_sprite(qb_sp_level_1_cube_animated_small, "level_1_cube_animated_small")
            .register_sprite(qb_sp_level_2_cube_animated, "level_2_cube_animated")
            .register_sprite(qb_sp_level_2_cube_animated_small, "level_2_cube_animated_small")
            .register_sprite(qb_sp_level_3_cube_animated, "level_3_cube_animated")
            .register_sprite(qb_sp_level_3_cube_animated_small, "level_3_cube_animated_small")
            .register_sprite(qb_sp_level_4_cube_animated, "level_4_cube_animated")
            .register_sprite(qb_sp_level_4_cube_animated_small, "level_4_cube_animated_small")
            .register_sprite(qb_sp_level_5_cube_animated, "level_5_cube_animated")
            .register_sprite(qb_sp_level_5_cube_animated_small, "level_5_cube_animated_small")
            .register_sprite(qb_sp_level_6_cube_animated, "level_6_cube_animated")
            .register_sprite(qb_sp_level_6_cube_animated_small, "level_6_cube_animated_small")
            .register_sprite(qb_sp_level_7_cube_animated, "level_7_cube_animated")
            .register_sprite(qb_sp_level_7_cube_animated_small, "level_7_cube_animated_small")
            .register_sprite(qb_sp_level_8_cube_animated, "level_8_cube_animated")
            .register_sprite(qb_sp_level_8_cube_animated_small, "level_8_cube_animated_small")
            .register_sprite(qb_sp_level_9_cube_animated, "level_9_cube_animated")
            .register_sprite(qb_sp_level_9_cube_animated_small, "level_9_cube_animated_small");
            
    }
}
