#pragma once

namespace qbert
{
    enum qbert_sprite
    {
        qb_sp_level_1_cube_1 = 11,
        qb_sp_level_1_cube_2,
        qb_sp_level_1_cube_3,
        qb_sp_level_1_cube_4,
        qb_sp_level_1_cube_5,
        qb_sp_level_1_cube_6,
        qb_sp_level_2_cube_1 = 21,
        qb_sp_level_2_cube_2,
        qb_sp_level_2_cube_3,
        qb_sp_level_2_cube_4,
        qb_sp_level_2_cube_5,
        qb_sp_level_2_cube_6,
        qb_sp_level_3_cube_1 = 31,
        qb_sp_level_3_cube_2,
        qb_sp_level_3_cube_3,
        qb_sp_level_3_cube_4,
        qb_sp_level_3_cube_5,
        qb_sp_level_3_cube_6,
        qb_sp_level_4_cube_1 = 41,
        qb_sp_level_4_cube_2,
        qb_sp_level_4_cube_3,
        qb_sp_level_4_cube_4,
        qb_sp_level_4_cube_5,
        qb_sp_level_4_cube_6,
        qb_sp_level_5_cube_1 = 51,
        qb_sp_level_5_cube_2,
        qb_sp_level_5_cube_3,
        qb_sp_level_5_cube_4,
        qb_sp_level_5_cube_5,
        qb_sp_level_5_cube_6,
        qb_sp_level_6_cube_1 = 61,
        qb_sp_level_6_cube_2,
        qb_sp_level_6_cube_3,
        qb_sp_level_6_cube_4,
        qb_sp_level_6_cube_5,
        qb_sp_level_6_cube_6,
        qb_sp_level_7_cube_1 = 71,
        qb_sp_level_7_cube_2,
        qb_sp_level_7_cube_3,
        qb_sp_level_7_cube_4,
        qb_sp_level_7_cube_5,
        qb_sp_level_7_cube_6,
        qb_sp_level_8_cube_1 = 81,
        qb_sp_level_8_cube_2,
        qb_sp_level_8_cube_3,
        qb_sp_level_8_cube_4,
        qb_sp_level_8_cube_5,
        qb_sp_level_8_cube_6,
        qb_sp_level_9_cube_1 = 91,
        qb_sp_level_9_cube_2,
        qb_sp_level_9_cube_3,
        qb_sp_level_9_cube_4,
        qb_sp_level_9_cube_5,
        qb_sp_level_9_cube_6,
        
        qb_sp_level_1_cube_1_small = 111,
        qb_sp_level_1_cube_2_small,
        qb_sp_level_1_cube_3_small,
        qb_sp_level_2_cube_1_small = 221,
        qb_sp_level_2_cube_2_small,
        qb_sp_level_2_cube_3_small,
        qb_sp_level_3_cube_1_small = 331,
        qb_sp_level_3_cube_2_small,
        qb_sp_level_3_cube_3_small,
        qb_sp_level_4_cube_1_small = 441,
        qb_sp_level_4_cube_2_small,
        qb_sp_level_4_cube_3_small,
        qb_sp_level_5_cube_1_small = 551,
        qb_sp_level_5_cube_2_small,
        qb_sp_level_5_cube_3_small,
        qb_sp_level_6_cube_1_small = 661,
        qb_sp_level_6_cube_2_small,
        qb_sp_level_6_cube_3_small,
        qb_sp_level_7_cube_1_small = 771,
        qb_sp_level_7_cube_2_small,
        qb_sp_level_7_cube_3_small,
        qb_sp_level_8_cube_1_small = 881,
        qb_sp_level_8_cube_2_small,
        qb_sp_level_8_cube_3_small,
        qb_sp_level_9_cube_1_small = 991,
        qb_sp_level_9_cube_2_small,
        qb_sp_level_9_cube_3_small,
        
        qb_sp_level_1_disk_1 = 1111,
        qb_sp_level_1_disk_2,
        qb_sp_level_2_disk_1 = 2221,
        qb_sp_level_2_disk_2,
        qb_sp_level_3_disk_1 = 3331,
        qb_sp_level_3_disk_2,
        qb_sp_level_4_disk_1 = 4441,
        qb_sp_level_4_disk_2,
        qb_sp_level_5_disk_1 = 5551,
        qb_sp_level_5_disk_2,
        qb_sp_level_6_disk_1 = 6661,
        qb_sp_level_6_disk_2,
        qb_sp_level_7_disk_1 = 7771,
        qb_sp_level_7_disk_2,
        qb_sp_level_8_disk_1 = 8881,
        qb_sp_level_8_disk_2,
        qb_sp_level_9_disk_1 = 9991,
        qb_sp_level_9_disk_2,
        
        qb_sp_qbert_player_1,
        qb_sp_qbert_player_2,
        qb_sp_ball_red,
        qb_sp_ball_green,
        qb_sp_coily_egg,
        qb_sp_coily,
        qb_sp_ugg,
        qb_sp_wrong_way,
        qb_sp_slick,
        qb_sp_sam,
        
        qb_sp_numbers_regular_orange,
        qb_sp_numbers_regular_purple,
        qb_sp_numbers_bold_orange,
        qb_sp_numbers_bold_pink,
        qb_sp_numbers_large_yellow,
        qb_sp_numbers_large_gray,
        
        qb_sp_alphabet_regular_green,
        qb_sp_alphabet_regular_purple,
        qb_sp_alphabet_regular_space,
        qb_sp_alphabet_bold_orange,
        qb_sp_alphabet_large_yellow,
        qb_sp_alphabet_large_gray,
        
        qb_sp_text_orange_player,
        qb_sp_text_purple_player,
        qb_sp_text_level,
        qb_sp_text_round,
        qb_sp_text_change_to,
        qb_sp_text_qbert,
        qb_sp_text_rotate_disk_color,
        qb_sp_text_one,
        qb_sp_text_two,
        qb_sp_text_large_yellow_qbert,
        qb_sp_text_large_gray_qbert,
        
        qb_sp_arrow_left,
        qb_sp_arrow_right,
        qb_sp_qbert_life,
        qb_sp_qbert_swearing,
        qb_sp_qbert_big,
    };
    
    void init_sprites();
}
